[package]
name = "simplepir"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32"
rand = "0.8"
rand_distr = "0.4"
rand_chacha = "0.3"
num-bigint = {version = "0.4.6", features = ["rand"]}
num-traits = "0.2.19"
